FROM caddy:builder AS builder

RUN xcaddy build \
    --with github.com/caddyserver/replace-response \
    --with github.com/caddyserver/cache-handler \
    --with github.com/corazawaf/coraza-caddy/v2

FROM caddy:latest

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
